Для вывода сообщения об ошибке используйте конструкцию
`try/catch` и отлавливайте `BattleException`. В случае
исключительной ситуации выведите сообщение об ошибке.